workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS app
        script: flutter build ios --release
