// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSo9Fl0Vm7jSG7sM8CaFbnEYAHqqWuxfM',
    appId: '1:820461626511:web:647a6b86e9f72ed2debcfa',
    messagingSenderId: '820461626511',
    projectId: 'credenciales-alumnos',
    authDomain: 'credenciales-alumnos.firebaseapp.com',
    storageBucket: 'credenciales-alumnos.appspot.com',
    measurementId: 'G-EFLEF71GNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtDZT9R1opG4B1VJxfJpbzBwux2Kqle90',
    appId: '1:820461626511:android:8ac3c764e3bfc452debcfa',
    messagingSenderId: '820461626511',
    projectId: 'credenciales-alumnos',
    storageBucket: 'credenciales-alumnos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaqlPJXZ-Bjs5RmFIyPuhvJuTi0Nem7Nk',
    appId: '1:820461626511:ios:fc247454efcf68acdebcfa',
    messagingSenderId: '820461626511',
    projectId: 'credenciales-alumnos',
    storageBucket: 'credenciales-alumnos.appspot.com',
    iosBundleId: 'com.example.credencialesAlumnos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaqlPJXZ-Bjs5RmFIyPuhvJuTi0Nem7Nk',
    appId: '1:820461626511:ios:fc247454efcf68acdebcfa',
    messagingSenderId: '820461626511',
    projectId: 'credenciales-alumnos',
    storageBucket: 'credenciales-alumnos.appspot.com',
    iosBundleId: 'com.example.credencialesAlumnos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSo9Fl0Vm7jSG7sM8CaFbnEYAHqqWuxfM',
    appId: '1:820461626511:web:0f7f4a2f35f391bddebcfa',
    messagingSenderId: '820461626511',
    projectId: 'credenciales-alumnos',
    authDomain: 'credenciales-alumnos.firebaseapp.com',
    storageBucket: 'credenciales-alumnos.appspot.com',
    measurementId: 'G-TE0GRTSJ7T',
  );
}
